### PR TITLE
Check for the condition where the suite is empty

### PR DESCRIPTION
**Pull request by mpahuja**

### CODE REVIEW

**Comment by vania-pooh** [comment]
Summon @smecsia, @9ikhan

**Comment by mpahuja** [comment]
Any update? This change may not work reliably but having some issues to test it!

**Comment by vania-pooh** [comment]
@mpahuja sorry for the delays but we have a week of holidays till next Monday so some developers will not probably be able to reply you till this day.

**Comment by smecsia** [comment]
@mpahuja I've added the check for empty suite (try to use 0.6.8 of allure-rspec). Not sure that it helps, since I have no problems with re-running locally.

**Pull request closed without merging**
